development:
    adapter: postgresql
    database: grades
    pool: 5
    username: grades
    password: grades
    host: localhost
    encoding: utf8
production:
    adapter: postgresql
    database: grades
    pool: 5
    username: grades
    password: grades
    host: localhost
    encoding: utf8
